---
name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-docker-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            sreevasmk1993/nodeapp-test:latest
            sreevasmk1993/nodeapp-test:${{ github.sha }}


      - name: Clone Helm repo
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Sreevas-MK/k8s-helm-nodeapp.git helm-temp
        shell: bash

      - name: Update Helm values.yaml
        run: |
          cd helm-temp
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml
          git config user.name "Sreevas-MK"
          git config user.email "sreevasmk@gmail.com"
          git add values.yaml
          git commit -m "Updated the docker image tag to ${{ github.sha }}"
          git push origin main
        shell: bash
